osx_image: xcode7.1
language: objective-c

podfile: Heyzap/Podfile

before_install: gem install cocoapods
script: bundle exec ./runTests.sh 9.0 IntegrationTestHost `pwd`/iOS9IntegrationTests

addons:
  artifacts: true
  debug: true
  paths:
    - find iOS9IntegrationTests -type f -name "action"

cache:
  - bundler
  - cocoapods