language: objective-c
xcode_workspace: Heyzap/Heyzap.xcworkspace
xcode_scheme: Ads
xcode_sdk: iphonesimulator7.0

env:
    global:
        # Necessary to work around some Travis-only bugs
        # (This should be set by Travis but is not currently:
        # https://github.com/travis-ci/travis-ci/issues/1769)
        - TRAVIS=true

before_install:
    - xctool -version # Travis has xctool 0.1.13 installed, but xctool only supports Kiwi on 0.1.14. Eventually we can remove this step, as its quite slow.
    - brew update && brew upgrade xctool
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - cd Heyzap && pod install && cd $TRAVIS_BUILD_DIR

script: sh runIntegrationTests.sh

notifications:
  hipchat:
    rooms:
      secure: Pmpj0iM7SY4XPx+6CUR4J3BB5s+UmsSIK848YpYSjuAvYsP0P5UfWcG2rWHDP7O2ueYsfHLejhOCeIL0ezb/emob+DzYRK0Msy1O03U2k3Md+htvi2hJEqlNaZzFguPpVlUrxyVELWD7xSre5r8HJsAggqmTvxXPl9CB7IR7hcs=
