source 'https://github.com/Heyzap/CocoapodsSource.git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!


platform :ios, '6.0'

target :MediationTestApp, :exclusive => true do
  # Chartboost has an official "ChartboostSDK" podspec, but it's often out of date.
  # HZChartboost is vendored by Heyzap.
  pod 'HZChartboost'
  pod 'AdColony' # Maintained by AdColony
  pod 'Google-Mobile-Ads-SDK' # Maintained by Google

  pod 'VungleAdvertiserSDK' # In Cocoapods, but outdated. Vendored by Heyzap
  pod 'AppLovin' # Vendored by Heyzap
  pod 'UnityAds' # Vendored by Heyzap
  pod 'FacebookAudienceNetwork' # Vendored by Heyzap
  pod 'HyprMX' #Vendored by Heyzap
  pod 'Masonry'
  pod 'Leadbolt' # Vendored by Heyzap
end

target :"Ads Tests", :exclusive => true do # Unit Tests
   pod 'Kiwi'
   pod 'OHHTTPStubs', :head # We need this PR: https://github.com/AliSoftware/OHHTTPStubs/pull/129; we can adopt 4.4.0 when it's released.
end

target 'IntegrationTests', :exclusive => true do
  pod 'KIF', :configurations => ['Debug']
  pod 'OCMockito'
  pod 'OHHTTPStubs', :head # See comment above
end