source 'https://github.com/Heyzap/CocoapodsSource.git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!


platform :ios, '7.0'

target :MediationTestApp, :exclusive => true do
  # Chartboost has an official "ChartboostSDK" podspec, but it's often out of date.
  # HZChartboost is vendored by Heyzap.
  pod 'HZChartboost'
  pod 'AdColony' # Maintained by AdColony
  pod 'Google-Mobile-Ads-SDK' # Maintained by Google
  pod 'VungleSDK-iOS' # Maintained by Vungle
  pod 'FBAudienceNetwork' # Maintained by Facebook
  pod 'AppLovin' # Vendored by Heyzap
  pod 'UnityAds' # Vendored by Heyzap
  pod 'HyprMX' #Vendored by Heyzap
  pod 'Masonry'
  pod 'Leadbolt' # Vendored by Heyzap
  pod 'HZInMobi' # Vendored by Heyzap
end

target :"Ads Tests", :exclusive => true do # Unit Tests
   pod 'Kiwi'
   pod 'OHHTTPStubs'
end

target 'IntegrationTestHost', :exclusive => true do
  pod 'Google-Mobile-Ads-SDK' # Maintained by Google
  pod 'FacebookAudienceNetwork'
end

target 'IntegrationTests', :exclusive => true do
  pod 'KIF', :configurations => ['Debug']
  pod 'OCMockito'
  pod 'OHHTTPStubs'
end